# NOTE: update this with your service name
service: fs-challenge-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-dws

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: us-east-1

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ dwsTable, Arn ]

functions:
  preSignUp:
    handler: lambda-triggers/auth-functions/pre-sign-up.main
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: PreSignUp
          existing: true
  createAuthChallenge:
    handler: lambda-triggers/auth-functions/create-auth-challenge.main
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: CreateAuthChallenge
          existing: true
  defineAuthChallenge:
    handler: lambda-triggers/auth-functions/define-auth-challenge.main
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: DefineAuthChallenge
          existing: true
  verifyAuthChallengeResponse:
    handler: lambda-triggers/auth-functions/verify-auth-challenge-response.main
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: VerifyAuthChallengeResponse
          existing: true
  postAuthentication:
    handler: lambda-triggers/auth-functions/post-authentication.main
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: PostAuthentication
          existing: true
  create:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /wus
    # - method: POST request
    handler: lambda-triggers/db-functions/create.main
    events:
      - http:
          path: dws
          cors: true
          method: post
          authorizer: aws_iam
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /wus/{id}
    # - method: GET request
    handler: lambda-triggers/db-functions/get.main
    events:
      - http:
          path: dws/{id}
          cors: true
          method: get
          authorizer: aws_iam
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: lambda-triggers/db-functions/list.main
    events:
      - http:
          path: dws
          cors: true
          method: get
          authorizer: aws_iam
  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /wus/{id}
    # - method: PUT request
    handler: lambda-triggers/db-functions/update.main
    events:
      - http:
          path: dws/{id}
          cors: true
          method: put
          authorizer: aws_iam
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /wus/{id}
    # - method: DELETE request
    handler: lambda-triggers/db-functions/delete.main
    events:
      - http:
          path: dws/{id}
          cors: true
          method: delete
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}